name: CI
on:
  pull_request: {}

jobs:
  ##
  ## Stage 1
  ##
  test-sanity:
    name: sanity
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: sudo rm -rf /usr/local/bin/kustomize
    - run: make test-sanity

  test-links:
    name: doc links
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - run: make test-links

  ##
  ## Stage 2
  ##
  ansible:
    needs: [test-sanity, test-links]
    name: ansible e2e
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: |
          sudo apt-get install python3 python3-pip
          pip3 install --upgrade setuptools pip
          pip install --user ansible~=2.9.13
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo rm -rf /usr/local/bin/kustomize
      - run: |
          make test-e2e-ansible test-e2e-ansible-molecule

  integration:
    needs: [ test-sanity, test-links ]
    name: subcommand and integration
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make test-e2e-integration

  go:
    needs: [test-sanity, test-links]
    name: go unit and e2e
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo rm -rf /usr/local/bin/kustomize
      - run: make test-unit test-e2e-go
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out

  helm:
    needs: [test-sanity, test-links]
    name: helm e2e
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo rm -rf /usr/local/bin/kustomize
      - run: make test-e2e-helm
